name: puzzlegame
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  palette_generator: ^0.3.3+3
  confetti: ^0.7.0
  flutter_animate: ^4.3.0
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  assets:
    - assets/images/piece1.jpg
    - assets/images/piece2.jpg
    - assets/images/piece3.jpg
    - assets/images/piece4.jpg
    - assets/images/piece5.jpg
    - assets/images/piece6.jpg
    - assets/images/piece7.jpg
    - assets/images/piece8.jpg
    - assets/images/piece9.jpg
    - assets/images/piece10.jpg
    - assets/images/piece11.jpg
    - assets/images/piece12.jpg
    - assets/images/piece13.jpg
    - assets/images/piece14.jpg
    - assets/images/piece15.jpg

  uses-material-design: true
